import '@/styles/global.scss';
import '@/styles/heroui.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Providers } from './provider';
import { lora } from '../../public/font/font';

const monserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Laxsik Ecolodge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${monserrat.className} ${monserrat.variable} ${lora.variable} h-full antialiased`}
      data-mode='light'>
      <body className='flex min-h-full flex-col'>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
