import { TRoom } from '../types/room-type';

export const ROOMS: TRoom[] = [
  {
    id: '1',
    title: 'DELUXE DOUBLE ROOM WITH BALCONY',
    description:
      'The spacious double room features air conditioning, a private balcony with mountain views, free Wi-Fi, a minibar, and a modern bathroom. Perfect for couples seeking comfort and relaxation.',
    price: 150,
    thumbnail: '/images/rooms/room.png',
    images: [
      '/images/slider0.png',
      '/images/slider1.png',
      '/images/slider2.png',
      '/images/slider3.png',
      '/images/slider4.png',
    ],
    bed: '1 King Bed',
    area: 50,
    capacity: 2,
    quantity: 10,
    status: 'available',
  },
  {
    id: '2',
    title: 'SUPERIOR GARDEN VIEW ROOM',
    description:
      'Enjoy a peaceful stay with lush garden views, modern amenities and elegant interior.',
    price: 120,
    thumbnail: '/images/rooms/room.png',
    images: [
      '/images/slider0.png',
      '/images/slider1.png',
      '/images/slider2.png',
      '/images/slider3.png',
      '/images/slider4.png',
    ],
    bed: '1 Queen Bed',
    area: 40,
    capacity: 2,
    quantity: 8,
    status: 'available',
  },
  {
    id: '3',
    title: 'FAMILY SUITE',
    description:
      'Perfect for families, featuring two bedrooms and a spacious living area.',
    price: 220,
    thumbnail: '/images/rooms/room.png',
    images: [
      '/images/rooms/gallery-1.png',
      '/images/rooms/gallery-2.png',
      '/images/rooms/gallery-3.png',
    ],
    bed: '2 Double Beds',
    area: 70,
    capacity: 4,
    quantity: 5,
    status: 'available',
  },
  {
    id: '4',
    title: 'PREMIUM MOUNTAIN VIEW ROOM',
    description:
      'Wake up to breathtaking mountain views from your private balcony.',
    price: 180,
    thumbnail: '/images/rooms/room.png',
    images: [
      '/images/rooms/gallery-1.png',
      '/images/rooms/gallery-2.png',
      '/images/rooms/gallery-3.png',
    ],
    bed: '1 King Bed',
    area: 55,
    capacity: 2,
    quantity: 6,
    status: 'maintenance',
  },
  {
    id: '5',
    title: 'HONEYMOON SUITE',
    description:
      'Romantic suite designed for couples with luxury bathtub and balcony.',
    price: 280,
    thumbnail: '/images/rooms/room.png',
    images: [
      '/images/rooms/gallery-1.png',
      '/images/rooms/gallery-2.png',
      '/images/rooms/gallery-3.png',
    ],
    bed: '1 King Bed',
    area: 65,
    capacity: 2,
    quantity: 3,
    status: 'available',
  },
  {
    id: '6',
    title: 'EXECUTIVE DELUXE ROOM',
    description:
      'Premium room for business travelers with workspace and mountain view.',
    price: 200,
    thumbnail: '/images/rooms/room.png',
    images: [
      '/images/rooms/gallery-1.png',
      '/images/rooms/gallery-2.png',
      '/images/rooms/gallery-3.png',
    ],
    bed: '1 King Bed',
    area: 60,
    capacity: 2,
    quantity: 4,
    status: 'inactive',
  },
];
